### ISSUE TITLE
Make summary-report.py accept arguments

### ISSUE THREAD

**Issue by sumeshpremraj** [sumeshpremraj/rundeck-scripts#1]
[summary-report.py](https://github.com/sumeshpremraj/rundeck-scripts/blob/master/summary-report.py) currently has variables like `BASE_URL` and `PROJECT` in the script, that the user needs to edit for each server.

Make the script take arguments from the command line. Something like:

``` bash
$ python summary-report.py -P 'Production' -f 'from@mail.com' -t 'to@mail.com' -s 'smtp.domain.com' -B 'https://rundeck.internal.domain.tld'
```

See CONTRIBUTING.md on how to send a PR.

**Comment by polaroi8d** [comment]
Hello @sumeshpremraj im intrested in this issue, but i have a question, on the recipients email argument ('-t') here can be only one email or more?

**Comment by sumeshpremraj** [comment]
@polaroi8d multiple recipients, since the script currently supports that.

**Comment by SilentFlame** [comment]
is this done?

I would like to help.

**Comment by SilentFlame** [comment]
at max for how many arguments do we have make the script?
i.e -p, is taken 1, -p and -f taken 2, like that how many?

**Comment by sumeshpremraj** [comment]
@SilentFlame this is not done yet.
You can go through the hardcoded variables at the start of the script, the idea is to take as many of them from the command line as possible.

Use defaults where they make sense, and make others mandatory. I'll leave these decisions to you :)

**Comment by Pratik151** [comment]
Hello, 
anyone is working on this? I would like to give this a try

**Comment by polaroi8d** [comment]
Hello @Pratik151 im working on the issue :)

**Comment by sumeshpremraj** [comment]
Assigning this issue to @polaroi8d. If you are unable to work on this, please let me know so that it can be marked available again.

**Comment by polaroi8d** [comment]
We can closed this issue right know, I thinks.

**Comment by sumeshpremraj** [comment]
Closed. Thanks @polaroi8d!
