### ISSUE TITLE
Make sender default to the SMTP auth user

### ISSUE THREAD

**Issue by sumeshpremraj** [sumeshpremraj/rundeck-scripts#3]
[summary-report.py](https://github.com/sumeshpremraj/rundeck-scripts/blob/master/summary-report.py) currently has two separate variables for sender email:
- `smtp_username`:  the address to authenticate to the SMTP server (along with its password contained in `smtp_password`)
- `sender`: address in the data-from, which appears in the email client

Make the required changes to use the `smtp_username` as `sender` by default.

You might want to wait for #1 to be fixed and merged so that it becomes a bit easier to fix this issue.

See README.md for details about the script, and CONTRIBUTING.md on how to send a PR.

**Comment by hiimbex** [comment]
Hi there! I'll try to make these changes
