### ISSUE TITLE
Allow user to specify SMTP port to connect to

### ISSUE THREAD

**Issue by sumeshpremraj** [sumeshpremraj/rundeck-scripts#4]
The SMTP port in [summary-report.py](https://github.com/sumeshpremraj/rundeck-scripts/blob/master/summary-report.py#L81) is currently hardcoded to 587.

Allow user to specify the port to connect to, via command line argument. If no port is specified, default to port 587.

You might want to wait for #1 to be fixed and merged so that it becomes a bit easier to fix this issue.

See README.md for details about the script, and CONTRIBUTING.md on how to send a PR.

**Comment by ghost** [comment]
Hey @sumeshpremraj 
I took a take at fixing this issue.
I did a little bit of testing, but I don't have a lot of time at the moment.
If you don't mind, please do more extensive testing yourself.
Pull request #9
