### ISSUE TITLE
Autodetect SMTP port to connect to

### ISSUE THREAD

**Issue by sumeshpremraj** [sumeshpremraj/rundeck-scripts#5]
[summary-report.py](https://github.com/sumeshpremraj/rundeck-scripts/blob/master/summary-report.py) currently has SMTP port hard coded.

There is already #3 to allow the user to specify the port via command line argument, this is an improvement over that issue.

Autodetect SMTP port by trying all the common ports one by one - 587, 465, 25. This should be done _only_ if the user does not specify a port.

You might want to wait for #1 and #3 to be fixed and merged so that it becomes a bit easier to work on this.

**Comment by Battleroid** [comment]
I'll go ahead and give this a try, I suppose I'll wait for #1 to be finished before I go ahead.
