### ISSUE TITLE
Add logging for summary-report.py

### ISSUE THREAD

**Issue by sumeshpremraj** [sumeshpremraj/rundeck-scripts#6]
Add logging to summary-report.py. Some suggestions:
- Log the start and end of script
- Log the number of jobs that failed. If no jobs failed, then log that.

**Comment by ronalddas** [comment]
Hi, can i do this? Also, what should i log at the start and end? Am using the logging module of python.

**Comment by sumeshpremraj** [comment]
@ronalddas sure. You can see my suggestions above, and also include anything more if you have ideas.
